<!DOCTYPE html>
<html lang="fr">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Abril+Fatface&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="public/css/style.css">
    <title>Page Animée en JS</title>
</head>

<body>
    <div class="lignes">
        <div class="l1"></div>
        <div class="l2"></div>
    </div>
    <div class="container-first">
        <h1><span>To </span><span>Smoke ? </span><span>Go </span><span> Vaping</span></h1>
        <div class="container-btns">
            <button class="btn-first b1">Shop</button>
            <button class="btn-first b2">Contact</button>
        </div>
    </div>

    <img src="public/ressources/img/logo.png" alt="logo" class="logo">

    <ul class="medias">
        <li class="bulle"><img src="public\ressources\img\facebook.png" alt="facebook" class="logo-medias"></li>
        <li class="bulle"><img src="public/ressources/img/instagram.png" alt="instagram" class="logo-medias"></li>
        <li class="bulle"><img src="public/ressources/img/youtube.png" alt="youtube" class="logo-medias"></li>
        <li class="bulle"><img src="public/ressources/img/github.png" alt="github" class="logo-medias"></li>
    </ul>



    <script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/3.5.1/gsap.min.js"></script>
    <script src="public/js/main.js"></script>
</body>

</html>