<head>
    <link rel="stylesheet" href="public/css/shop-style2.css">
</head>

<body>
    <main>


        <img class="logotaille" src="public/ressources/img/logo.png">
        <h1> Nom Boutique </h1>

        <section class="sec1">
            <h2><span>To </span><span>Smoke ? </span><span>Go </span><span> Vaping</span></h2>
            <ul>
                <li class="puces">
                    <p><i class="fas fa-eye-dropper"></i></i> E-liquide 100% Français</p>
                </li>
                <li class="puces">
                    <p><i class="fas fa-truck"></i> Livraison rapide sous 48h</p>
                </li>
                <li class="puces">
                    <p><i class="fas fa-check"></i> Qualité garentie</p>
                </li>
                <li class="puces">
                    <p><i class="fas fa-credit-card"></i> Paiement sécurisé</p>
                </li>
            </ul>
        </section>

        <section class="sec2">
        <h3>Nos top catégories</h3>
            <div class="flex1">
                <div class="items1 vapcover">
                    <h4>Les Vapoteuses</h4>
                </div>
    
                <div class="items1 eliquidecover">
                    <h4>E-liquides</h4>
                </div>
                <div class="items1 accesoirescover">
                    <h4>Accesoires</h4>
                </div>
            </div>
        </section>

        <section class="sec3">
            <div class="flex2">
                <article class="items2">
                    <h3>Qui somme-nous ?</h3>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Doloribus sed maxime minus qui iste sapiente! Nihil recusandae corporis voluptas quaerat quia vitae, harum alias repudiandae similique consequatur deserunt hic distinctio nemo, laudantium eius quo ad quam mollitia. Rem cupiditate, commodi quis consequuntur eius, tenetur, magni odio perspiciatis voluptatibus ut non.</p>
                    <br>
                    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Harum necessitatibus illum maxime assumenda enim ab magnam quo velit, eos dignissimos placeat atque consequuntur. Porro non neque eaque temporibus sint odit dignissimos dolorem tenetur voluptas labore expedita consequatur officia, dicta aperiam suscipit amet quaerat? Hic accusamus aliquam harum magni tenetur cum voluptates repellendus nisi, tempora deleniti corporis dicta fugiat neque, eaque dignissimos nostrum, qui aperiam nihil rem. Blanditiis aliquam cumque voluptas accusantium similique dignissimos molestias velit cum quas, inventore magni eaque, iure autem, enim natus animi voluptatibus nihil? Odit minima consequatur, incidunt culpa accusantium ut repellat cum mollitia minus impedit iure.</p>
                    <br>
                    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Inventore vero id officia ipsa sequi quam a, est repellendus omnis neque?</p>

                    <button class="btn-first b1">A propos</button>
                </article>

                <article class="items2">
                    <h3>Pourquoi passez à la Vap ?</h3>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Doloribus sed maxime minus qui iste sapiente! Nihil recusandae corporis voluptas quaerat quia vitae, harum alias repudiandae similique consequatur deserunt hic distinctio nemo, laudantium eius quo ad quam mollitia. Rem cupiditate, commodi quis consequuntur eius, tenetur, magni odio perspiciatis voluptatibus ut non.</p>
                    <br>
                    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Harum necessitatibus illum maxime assumenda enim ab magnam quo velit, eos dignissimos placeat atque consequuntur. Porro non neque eaque temporibus sint odit dignissimos dolorem tenetur voluptas labore expedita consequatur officia, dicta aperiam suscipit amet quaerat? Hic accusamus aliquam harum magni tenetur cum voluptates repellendus nisi, tempora deleniti corporis dicta fugiat neque, eaque dignissimos nostrum, qui aperiam nihil rem. Blanditiis aliquam cumque voluptas accusantium similique dignissimos molestias velit cum quas, inventore magni eaque, iure autem, enim natus animi voluptatibus nihil? Odit minima consequatur, incidunt culpa accusantium ut repellat cum mollitia minus impedit iure.</p>
                    <br>
                    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Inventore vero id officia ipsa sequi quam a, est repellendus omnis neque?</p>

                    <button class="btn-first b1">En savoir plus</button>
                </article>
            </div>
        </section>


    </main>
</body>