<head>
    <link rel="stylesheet" href="public/css/shop-style2.css">
</head>
<h1>Inscription</h1>

<!-- ERREURS FORMULAIRE -->
<?php if (!empty($errorsForm)) : ?>
    <?php foreach ($errorsForm as $error) : ?>
        <div class="msgError">
            <p><?= $error ?></p>
        </div>
    <?php endforeach; ?>
<?php endif; ?>
<!-- FIN ERREURS FORMULAIRE -->

<!-- MSG VALID -->
<?php if (!empty($msgValid)) : ?>
    <?php foreach ($msgValid as $msg) : ?>
        <div class="msgValid">
            <p><?= $msg ?></p>
        </div>
    <?php endforeach; ?>
<?php endif; ?>
<!-- FIN MSG VALID -->

<div class="formInscription">
    <div class="box">
        <form method="POST" action="" class="formbloc">

            <h3><strong>Inscrivez</strong>-vous</h3>

            <div class="formGroupe">
                <label for="nom" class="form-label">Nom </label>
                <input type="text" class="form-control" id="nom" name="nom">
            </div>

            <div class="formGroupe">
                <label for="prenom" class="form-label">Prenom </label>
                <input type="text" class="form-control" id="prenom" name="prenom">
            </div>

            <div class="formGroupe">
                <label for="email" class="form-label">Adresse email </label>
                <input type="email" class="form-control" id="email" name="email" aria-describedby="emailHelp">
            </div>

            <div class="formGroupe">
                <label for="mdp" class="form-label">Mot de Passe</label>
                <input type="password" class="form-control" id="mdp" name="mdp">
            </div>

            <div class="formGroupe">
                <button type="submit" class="btnSubmit">S'inscrire</button>
            </div>

            <div class="mdpPerdu">
                <a href="#">Mot de passe perdu ?</a>
            </div>
        </form>
    </div>
</div>